# Changes here will be overwritten by Copier
_commit: v1.3.3
_src_path: gh:lincc-frameworks/python-project-template
author_email: brantd@uw.edu
author_name: Doug Branton
create_example_module: true
custom_install: true
include_notebooks: true
module_name: lsstseries
mypy_type_checking: none
preferred_linter: black
project_license: MIT
project_name: lsstseries
use_gitlfs: none
use_isort: false
