name: Benchmark
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write
  deployments: write

jobs:
  benchmark:
    # if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.10', '3.10', '3.10']

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        sudo apt-get update
        python -m pip install --upgrade pip
        pip install .
        pip install .[dev]
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run benchmark
      run: |
        pytest tests/tape_tests/bench.py --benchmark-json output.json

    - name: Store benchmark result
      uses: benchmark-action/github-action-benchmark@v1
      with:
        name: TAPE Benchmarking Monitor
        tool: 'pytest'
        output-file-path: output.json
        gh-pages-branch: gh-pages
        # Use personal access token instead of GITHUB_TOKEN due to https://github.community/t/github-action-not-triggering-gh-pages-upon-push/16096
        github-token: ${{ secrets.PAGES_TOKEN }}
        auto-push: true
        # Show alert with commit comment on detecting possible performance regression
        alert-threshold: '200%'
        comment-on-alert: true
        fail-on-alert: true
